// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jKBRszXoza5fn5dAcwSRHs3MjNGFvaA',
    appId: '1:1057757038546:web:a68a303f6ea1a1bafcaa0b',
    messagingSenderId: '1057757038546',
    projectId: 'fittrack-pro-ee867',
    authDomain: 'fittrack-pro-ee867.firebaseapp.com',
    storageBucket: 'fittrack-pro-ee867.firebasestorage.app',
    measurementId: 'G-NC3FT9T7ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_baRRlbLu3aPD3DGD7ID_kMUEsa0s7s',
    appId: '1:1057757038546:android:183d678391e5b0fdfcaa0b',
    messagingSenderId: '1057757038546',
    projectId: 'fittrack-pro-ee867',
    storageBucket: 'fittrack-pro-ee867.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABPERWYhjUgMRoSgbOsPSetia4jG-jILg',
    appId: '1:563071719296:ios:ca91ab5added380097d365',
    messagingSenderId: '563071719296',
    projectId: 'device-streaming-0528aebc',
    storageBucket: 'device-streaming-0528aebc.firebasestorage.app',
    iosBundleId: 'com.example.fittrackPro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABPERWYhjUgMRoSgbOsPSetia4jG-jILg',
    appId: '1:563071719296:ios:ca91ab5added380097d365',
    messagingSenderId: '563071719296',
    projectId: 'device-streaming-0528aebc',
    storageBucket: 'device-streaming-0528aebc.firebasestorage.app',
    iosBundleId: 'com.example.fittrackPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8droJbMaxyJZHp8PrLcbAVMLMp1APVFo',
    appId: '1:563071719296:web:dc693336a74f470497d365',
    messagingSenderId: '563071719296',
    projectId: 'device-streaming-0528aebc',
    authDomain: 'device-streaming-0528aebc.firebaseapp.com',
    storageBucket: 'device-streaming-0528aebc.firebasestorage.app',
  );
}
